GET http://127.0.0.1:8000/api/v1/movies/

###

GET http://127.0.0.1:8000/api/v1/movies/1/

###
POST http://127.0.0.1:8000/api/v1/movies/
Content-Type: application/json

{
    "title": "Superman",
    "duration": 110,
    "genres": [1]
}

### 
PUT http://127.0.0.1:8000/api/v1/movies/4/
Content-Type: application/json

{
    "title": "Superman II",
    "genres": [1]
}

###
DELETE http://127.0.0.1:8000/api/v1/movies/4/

###
GET http://127.0.0.1:8000/api/v1/movies/?genres=2&search=thri

### with ordering
GET http://127.0.0.1:8000/api/v1/movies/?genres=2&search=&ordering=title
